### ISSUE TITLE
Missing label in checkbox in some moodle instances

### ISSUE THREAD

**Issue by hpawe01** [PW-Solutions/miquiz-moodle#5]
The following lines in `mod_form.php` are rendered differently depending on moodle instance:

```php
        $gameModes = [];
        $gameModes[] = $mform->createElement('advcheckbox', 'game_mode_random_fight', get_string('miquiz_create_game_mode_random_fight', 'miquiz'));
        $gameModes[] = $mform->createElement('advcheckbox', 'game_mode_picked_fight', get_string('miquiz_create_game_mode_picked_fight', 'miquiz'));
        $mform->addGroup($gameModes, 'game_modes', get_string('miquiz_create_game_modes', 'miquiz'), ['<br>'], false);
        $mform->addHelpButton('game_modes', 'miquiz_create_game_modes', 'miquiz');
        $mform->setDefault('game_mode_random_fight', '1');
```

In local environment it is rendered the following:
<img width="826" alt="20190818_bug_checkbox_local" src="https://user-images.githubusercontent.com/1616302/63225265-3e0d6600-c1ce-11e9-8336-9a5e8fe10102.PNG">

But in another moodle instance it is missing:
<img width="765" alt="20190818_bug_checkbox_ecampus" src="https://user-images.githubusercontent.com/1616302/63225295-71e88b80-c1ce-11e9-983a-cd8319d3edfb.PNG">

How should we add the fields, so that the labels are visible independent of the moodle instance?

**Comment by nscbrandb** [comment]
there's nothing wrong with your code, the problem is the theme "clean" which has benn removed with Moodle 3.7
switching to boost helps ;-)

**Comment by hpawe01** [comment]
Just got time to look into this again. Is this something the normal user can do? Or do we need to make sure to support also the "clean" theme which is used e.g. in the eCampus instance?

**Comment by nscbrandb** [comment]
I don't know if there is another moodle instance which still runs the clean theme but I doubt it.
for our eCampus I'll force the boost theme for users so we won't run into this problem again

**Comment by hpawe01** [comment]
Okay, LGTM. Fixed by using a recent theme in Moodle.
